image: node:18

stages:
  - test
  - publish

variables:
  CI_REGISTRY: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
  # Use a custom cache location so we can cache node_modules
  NPM_CONFIG_CACHE: ${CI_PROJECT_DIR}/.npm
  # Tell npm to always use the cache
  NPM_CONFIG_PREFER_OFFLINE: "true"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  stage: test
  script:
    - npm ci
    - npm run build
    - npm test

publish:
  stage: publish
  image: node:18
  script:
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm config set @${CI_PROJECT_ROOT_NAMESPACE}:registry ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
    - npm ci
    - npm run build
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH != null
      when: manual
      allow_failure: true
