/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccessLevel = {
    Admin: 'ADMIN',
    Commenter: 'COMMENTER',
    Editor: 'EDITOR',
    EditorShare: 'EDITOR_SHARE',
    Owner: 'OWNER',
    Viewer: 'VIEWER'
} as const;
export type AccessLevel = typeof AccessLevel[keyof typeof AccessLevel];


export function instanceOfAccessLevel(value: any): boolean {
    for (const key in AccessLevel) {
        if (Object.prototype.hasOwnProperty.call(AccessLevel, key)) {
            if (AccessLevel[key as keyof typeof AccessLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccessLevelFromJSON(json: any): AccessLevel {
    return AccessLevelFromJSONTyped(json, false);
}

export function AccessLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessLevel {
    return json as AccessLevel;
}

export function AccessLevelToJSON(value?: AccessLevel | null): any {
    return value as any;
}

export function AccessLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): AccessLevel {
    return value as AccessLevel;
}

