/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AlternateEmail } from './AlternateEmail';
import {
    AlternateEmailFromJSON,
    AlternateEmailFromJSONTyped,
    AlternateEmailToJSON,
    AlternateEmailToJSONTyped,
} from './AlternateEmail';

/**
 * 
 * @export
 * @interface AddAlternateEmail200Response
 */
export interface AddAlternateEmail200Response {
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof AddAlternateEmail200Response
     */
    message?: AddAlternateEmail200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof AddAlternateEmail200Response
     */
    resultCode?: AddAlternateEmail200ResponseResultCodeEnum;
    /**
     * Updated User Properties
     * @type {Array<AlternateEmail>}
     * @memberof AddAlternateEmail200Response
     */
    data?: Array<AlternateEmail>;
}


/**
 * @export
 */
export const AddAlternateEmail200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type AddAlternateEmail200ResponseMessageEnum = typeof AddAlternateEmail200ResponseMessageEnum[keyof typeof AddAlternateEmail200ResponseMessageEnum];

/**
 * @export
 */
export const AddAlternateEmail200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type AddAlternateEmail200ResponseResultCodeEnum = typeof AddAlternateEmail200ResponseResultCodeEnum[keyof typeof AddAlternateEmail200ResponseResultCodeEnum];


/**
 * Check if a given object implements the AddAlternateEmail200Response interface.
 */
export function instanceOfAddAlternateEmail200Response(value: object): value is AddAlternateEmail200Response {
    return true;
}

export function AddAlternateEmail200ResponseFromJSON(json: any): AddAlternateEmail200Response {
    return AddAlternateEmail200ResponseFromJSONTyped(json, false);
}

export function AddAlternateEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAlternateEmail200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AlternateEmailFromJSON)),
    };
}

export function AddAlternateEmail200ResponseToJSON(json: any): AddAlternateEmail200Response {
    return AddAlternateEmail200ResponseToJSONTyped(json, false);
}

export function AddAlternateEmail200ResponseToJSONTyped(value?: AddAlternateEmail200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resultCode': value['resultCode'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AlternateEmailToJSON)),
    };
}

