/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AddFavoriteRequest } from './AddFavoriteRequest';
import {
    AddFavoriteRequestFromJSON,
    AddFavoriteRequestFromJSONTyped,
    AddFavoriteRequestToJSON,
    AddFavoriteRequestToJSONTyped,
} from './AddFavoriteRequest';

/**
 * 
 * @export
 * @interface AddFavorite200Response
 */
export interface AddFavorite200Response {
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof AddFavorite200Response
     */
    message?: AddFavorite200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof AddFavorite200Response
     */
    resultCode?: AddFavorite200ResponseResultCodeEnum;
    /**
     * 
     * @type {AddFavoriteRequest}
     * @memberof AddFavorite200Response
     */
    result?: AddFavoriteRequest;
}


/**
 * @export
 */
export const AddFavorite200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type AddFavorite200ResponseMessageEnum = typeof AddFavorite200ResponseMessageEnum[keyof typeof AddFavorite200ResponseMessageEnum];

/**
 * @export
 */
export const AddFavorite200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type AddFavorite200ResponseResultCodeEnum = typeof AddFavorite200ResponseResultCodeEnum[keyof typeof AddFavorite200ResponseResultCodeEnum];


/**
 * Check if a given object implements the AddFavorite200Response interface.
 */
export function instanceOfAddFavorite200Response(value: object): value is AddFavorite200Response {
    return true;
}

export function AddFavorite200ResponseFromJSON(json: any): AddFavorite200Response {
    return AddFavorite200ResponseFromJSONTyped(json, false);
}

export function AddFavorite200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFavorite200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : AddFavoriteRequestFromJSON(json['result']),
    };
}

export function AddFavorite200ResponseToJSON(json: any): AddFavorite200Response {
    return AddFavorite200ResponseToJSONTyped(json, false);
}

export function AddFavorite200ResponseToJSONTyped(value?: AddFavorite200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': AddFavoriteRequestToJSON(value['result']),
    };
}

