/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AddGroupMembersRequest } from './AddGroupMembersRequest';
import {
    AddGroupMembersRequestFromJSON,
    AddGroupMembersRequestFromJSONTyped,
    AddGroupMembersRequestToJSON,
    AddGroupMembersRequestToJSONTyped,
} from './AddGroupMembersRequest';

/**
 * 
 * @export
 * @interface AddGroupMembers200Response
 */
export interface AddGroupMembers200Response {
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof AddGroupMembers200Response
     */
    message?: AddGroupMembers200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof AddGroupMembers200Response
     */
    resultCode?: AddGroupMembers200ResponseResultCodeEnum;
    /**
     * 
     * @type {AddGroupMembersRequest}
     * @memberof AddGroupMembers200Response
     */
    result?: AddGroupMembersRequest;
}


/**
 * @export
 */
export const AddGroupMembers200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type AddGroupMembers200ResponseMessageEnum = typeof AddGroupMembers200ResponseMessageEnum[keyof typeof AddGroupMembers200ResponseMessageEnum];

/**
 * @export
 */
export const AddGroupMembers200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type AddGroupMembers200ResponseResultCodeEnum = typeof AddGroupMembers200ResponseResultCodeEnum[keyof typeof AddGroupMembers200ResponseResultCodeEnum];


/**
 * Check if a given object implements the AddGroupMembers200Response interface.
 */
export function instanceOfAddGroupMembers200Response(value: object): value is AddGroupMembers200Response {
    return true;
}

export function AddGroupMembers200ResponseFromJSON(json: any): AddGroupMembers200Response {
    return AddGroupMembers200ResponseFromJSONTyped(json, false);
}

export function AddGroupMembers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddGroupMembers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : AddGroupMembersRequestFromJSON(json['result']),
    };
}

export function AddGroupMembers200ResponseToJSON(json: any): AddGroupMembers200Response {
    return AddGroupMembers200ResponseToJSONTyped(json, false);
}

export function AddGroupMembers200ResponseToJSONTyped(value?: AddGroupMembers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': AddGroupMembersRequestToJSON(value['result']),
    };
}

