/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group';

/**
 * 
 * @export
 * @interface AddGroup200Response
 */
export interface AddGroup200Response {
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof AddGroup200Response
     */
    message?: AddGroup200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof AddGroup200Response
     */
    resultCode?: AddGroup200ResponseResultCodeEnum;
    /**
     * 
     * @type {Group}
     * @memberof AddGroup200Response
     */
    result?: Group;
}


/**
 * @export
 */
export const AddGroup200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type AddGroup200ResponseMessageEnum = typeof AddGroup200ResponseMessageEnum[keyof typeof AddGroup200ResponseMessageEnum];

/**
 * @export
 */
export const AddGroup200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type AddGroup200ResponseResultCodeEnum = typeof AddGroup200ResponseResultCodeEnum[keyof typeof AddGroup200ResponseResultCodeEnum];


/**
 * Check if a given object implements the AddGroup200Response interface.
 */
export function instanceOfAddGroup200Response(value: object): value is AddGroup200Response {
    return true;
}

export function AddGroup200ResponseFromJSON(json: any): AddGroup200Response {
    return AddGroup200ResponseFromJSONTyped(json, false);
}

export function AddGroup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddGroup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : GroupFromJSON(json['result']),
    };
}

export function AddGroup200ResponseToJSON(json: any): AddGroup200Response {
    return AddGroup200ResponseToJSONTyped(json, false);
}

export function AddGroup200ResponseToJSONTyped(value?: AddGroup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': GroupToJSON(value['result']),
    };
}

