/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AutomationRule } from './AutomationRule';
import {
    AutomationRuleFromJSON,
    AutomationRuleFromJSONTyped,
    AutomationRuleToJSON,
    AutomationRuleToJSONTyped,
} from './AutomationRule';
import type { BulkItemFailure } from './BulkItemFailure';
import {
    BulkItemFailureFromJSON,
    BulkItemFailureFromJSONTyped,
    BulkItemFailureToJSON,
    BulkItemFailureToJSONTyped,
} from './BulkItemFailure';

/**
 * 
 * @export
 * @interface AutomationruleUpdate200Response
 */
export interface AutomationruleUpdate200Response {
    /**
     * New version of the sheet. Applicable only for operations which update sheet data.
     * @type {number}
     * @memberof AutomationruleUpdate200Response
     */
    version?: number | null;
    /**
     * Array of BulkItemFailure objects which represents the items that failed to be added or updated. See [Bulk operations > Partial success](/api/smartsheet/guides/advanced-topics/scalability-options) for more information. Applicable only for bulk operations that support partial success.
     * @type {Array<BulkItemFailure>}
     * @memberof AutomationruleUpdate200Response
     */
    failedItems?: Array<BulkItemFailure> | null;
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof AutomationruleUpdate200Response
     */
    message?: AutomationruleUpdate200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof AutomationruleUpdate200Response
     */
    resultCode?: AutomationruleUpdate200ResponseResultCodeEnum;
    /**
     * 
     * @type {AutomationRule}
     * @memberof AutomationruleUpdate200Response
     */
    result?: AutomationRule;
}


/**
 * @export
 */
export const AutomationruleUpdate200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type AutomationruleUpdate200ResponseMessageEnum = typeof AutomationruleUpdate200ResponseMessageEnum[keyof typeof AutomationruleUpdate200ResponseMessageEnum];

/**
 * @export
 */
export const AutomationruleUpdate200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type AutomationruleUpdate200ResponseResultCodeEnum = typeof AutomationruleUpdate200ResponseResultCodeEnum[keyof typeof AutomationruleUpdate200ResponseResultCodeEnum];


/**
 * Check if a given object implements the AutomationruleUpdate200Response interface.
 */
export function instanceOfAutomationruleUpdate200Response(value: object): value is AutomationruleUpdate200Response {
    return true;
}

export function AutomationruleUpdate200ResponseFromJSON(json: any): AutomationruleUpdate200Response {
    return AutomationruleUpdate200ResponseFromJSONTyped(json, false);
}

export function AutomationruleUpdate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutomationruleUpdate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'failedItems': json['failedItems'] == null ? undefined : ((json['failedItems'] as Array<any>).map(BulkItemFailureFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : AutomationRuleFromJSON(json['result']),
    };
}

export function AutomationruleUpdate200ResponseToJSON(json: any): AutomationruleUpdate200Response {
    return AutomationruleUpdate200ResponseToJSONTyped(json, false);
}

export function AutomationruleUpdate200ResponseToJSONTyped(value?: AutomationruleUpdate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'failedItems': value['failedItems'] == null ? undefined : ((value['failedItems'] as Array<any>).map(BulkItemFailureToJSON)),
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': AutomationRuleToJSON(value['result']),
    };
}

