/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface CommentsCreate200Response
 */
export interface CommentsCreate200Response {
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof CommentsCreate200Response
     */
    message?: CommentsCreate200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof CommentsCreate200Response
     */
    resultCode?: CommentsCreate200ResponseResultCodeEnum;
    /**
     * 
     * @type {Comment}
     * @memberof CommentsCreate200Response
     */
    result?: Comment;
}


/**
 * @export
 */
export const CommentsCreate200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type CommentsCreate200ResponseMessageEnum = typeof CommentsCreate200ResponseMessageEnum[keyof typeof CommentsCreate200ResponseMessageEnum];

/**
 * @export
 */
export const CommentsCreate200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type CommentsCreate200ResponseResultCodeEnum = typeof CommentsCreate200ResponseResultCodeEnum[keyof typeof CommentsCreate200ResponseResultCodeEnum];


/**
 * Check if a given object implements the CommentsCreate200Response interface.
 */
export function instanceOfCommentsCreate200Response(value: object): value is CommentsCreate200Response {
    return true;
}

export function CommentsCreate200ResponseFromJSON(json: any): CommentsCreate200Response {
    return CommentsCreate200ResponseFromJSONTyped(json, false);
}

export function CommentsCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsCreate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : CommentFromJSON(json['result']),
    };
}

export function CommentsCreate200ResponseToJSON(json: any): CommentsCreate200Response {
    return CommentsCreate200ResponseToJSONTyped(json, false);
}

export function CommentsCreate200ResponseToJSONTyped(value?: CommentsCreate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': CommentToJSON(value['result']),
    };
}

