/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * List of supported fonts in Dashboards
 * @export
 */
export const DashboardFont = {
    Arial: 'Arial',
    Courier: 'Courier',
    Georgia: 'Georgia',
    GillSans: 'Gill Sans',
    Helvetica: 'Helvetica',
    Luminari: 'Luminari',
    Monaco: 'Monaco',
    Tahoma: 'Tahoma',
    TimesNewRoman: 'Times New Roman',
    Verdana: 'Verdana'
} as const;
export type DashboardFont = typeof DashboardFont[keyof typeof DashboardFont];


export function instanceOfDashboardFont(value: any): boolean {
    for (const key in DashboardFont) {
        if (Object.prototype.hasOwnProperty.call(DashboardFont, key)) {
            if (DashboardFont[key as keyof typeof DashboardFont] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DashboardFontFromJSON(json: any): DashboardFont {
    return DashboardFontFromJSONTyped(json, false);
}

export function DashboardFontFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardFont {
    return json as DashboardFont;
}

export function DashboardFontToJSON(value?: DashboardFont | null): any {
    return value as any;
}

export function DashboardFontToJSONTyped(value: any, ignoreDiscriminator: boolean): DashboardFont {
    return value as DashboardFont;
}

