/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object representing a date
 * @export
 * @interface DateObjectValue
 */
export interface DateObjectValue {
    /**
     * 
     * @type {string}
     * @memberof DateObjectValue
     */
    objectType?: DateObjectValueObjectTypeEnum;
    /**
     * Date in the **full-date** format defined by [(https://tools.ietf.org/html/rfc3339#section-5.6" target="_blank" rel="noopener noreferrer">RFC 3339, section 5.6]</a>
     * @type {Date}
     * @memberof DateObjectValue
     */
    value?: Date;
}


/**
 * @export
 */
export const DateObjectValueObjectTypeEnum = {
    Date: 'DATE'
} as const;
export type DateObjectValueObjectTypeEnum = typeof DateObjectValueObjectTypeEnum[keyof typeof DateObjectValueObjectTypeEnum];


/**
 * Check if a given object implements the DateObjectValue interface.
 */
export function instanceOfDateObjectValue(value: object): value is DateObjectValue {
    return true;
}

export function DateObjectValueFromJSON(json: any): DateObjectValue {
    return DateObjectValueFromJSONTyped(json, false);
}

export function DateObjectValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateObjectValue {
    if (json == null) {
        return json;
    }
    return {
        
        'objectType': json['objectType'] == null ? undefined : json['objectType'],
        'value': json['value'] == null ? undefined : (new Date(json['value'])),
    };
}

export function DateObjectValueToJSON(json: any): DateObjectValue {
    return DateObjectValueToJSONTyped(json, false);
}

export function DateObjectValueToJSONTyped(value?: DateObjectValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectType': value['objectType'],
        'value': value['value'] == null ? undefined : ((value['value']).toISOString().substring(0,10)),
    };
}

