/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Recipient } from './Recipient';
import {
    RecipientFromJSON,
    RecipientFromJSONTyped,
    RecipientToJSON,
    RecipientToJSONTyped,
} from './Recipient';

/**
 * 
 * @export
 * @interface Email
 */
export interface Email {
    /**
     * Indicates whether to send a copy of the email to the sender.
     * @type {boolean}
     * @memberof Email
     */
    ccMe?: boolean;
    /**
     * The message of the email.
     * @type {string}
     * @memberof Email
     */
    message?: string;
    /**
     * Array of recipients.
     * @type {Array<Recipient>}
     * @memberof Email
     */
    sendTo?: Array<Recipient>;
    /**
     * The subject of the email.
     * @type {string}
     * @memberof Email
     */
    subject?: string;
}

/**
 * Check if a given object implements the Email interface.
 */
export function instanceOfEmail(value: object): value is Email {
    return true;
}

export function EmailFromJSON(json: any): Email {
    return EmailFromJSONTyped(json, false);
}

export function EmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): Email {
    if (json == null) {
        return json;
    }
    return {
        
        'ccMe': json['ccMe'] == null ? undefined : json['ccMe'],
        'message': json['message'] == null ? undefined : json['message'],
        'sendTo': json['sendTo'] == null ? undefined : ((json['sendTo'] as Array<any>).map(RecipientFromJSON)),
        'subject': json['subject'] == null ? undefined : json['subject'],
    };
}

export function EmailToJSON(json: any): Email {
    return EmailToJSONTyped(json, false);
}

export function EmailToJSONTyped(value?: Email | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ccMe': value['ccMe'],
        'message': value['message'],
        'sendTo': value['sendTo'] == null ? undefined : ((value['sendTo'] as Array<any>).map(RecipientToJSON)),
        'subject': value['subject'],
    };
}

