/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Container object for additional event-specific properties. Properties depend upon the event type, but all events include an `emailaddress` property, representing the user responsible for the activity. See <a href="https://smartsheet-platform.github.io/event-reporting-docs/" target="_blank" rel="noopener noreferrer">Event Reporting</a> reference documentation for details on each event type.
 * @export
 * @interface EventAdditionalDetails
 */
export interface EventAdditionalDetails {
    [key: string]: any | any;
    /**
     * Email address of the user responsible for the activity.
     * @type {string}
     * @memberof EventAdditionalDetails
     */
    emailAddress: string;
}

/**
 * Check if a given object implements the EventAdditionalDetails interface.
 */
export function instanceOfEventAdditionalDetails(value: object): value is EventAdditionalDetails {
    if (!('emailAddress' in value) || value['emailAddress'] === undefined) return false;
    return true;
}

export function EventAdditionalDetailsFromJSON(json: any): EventAdditionalDetails {
    return EventAdditionalDetailsFromJSONTyped(json, false);
}

export function EventAdditionalDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventAdditionalDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'emailAddress': json['emailAddress'],
    };
}

export function EventAdditionalDetailsToJSON(json: any): EventAdditionalDetails {
    return EventAdditionalDetailsToJSONTyped(json, false);
}

export function EventAdditionalDetailsToJSONTyped(value?: EventAdditionalDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'emailAddress': value['emailAddress'],
    };
}

