/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface Favorite
 */
export interface Favorite {
    /**
     * The Id of the favorited item. If type is template, only private sheet-type template Id is allowed.
     * @type {number}
     * @memberof Favorite
     */
    objectId?: number;
    /**
     * 
     * @type {string}
     * @memberof Favorite
     */
    type?: FavoriteTypeEnum;
}


/**
 * @export
 */
export const FavoriteTypeEnum = {
    Folder: 'folder',
    Report: 'report',
    Sheet: 'sheet',
    Sight: 'sight',
    Template: 'template',
    Workspace: 'workspace'
} as const;
export type FavoriteTypeEnum = typeof FavoriteTypeEnum[keyof typeof FavoriteTypeEnum];


/**
 * Check if a given object implements the Favorite interface.
 */
export function instanceOfFavorite(value: object): value is Favorite {
    return true;
}

export function FavoriteFromJSON(json: any): Favorite {
    return FavoriteFromJSONTyped(json, false);
}

export function FavoriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Favorite {
    if (json == null) {
        return json;
    }
    return {
        
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function FavoriteToJSON(json: any): Favorite {
    return FavoriteToJSONTyped(json, false);
}

export function FavoriteToJSONTyped(value?: Favorite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectId': value['objectId'],
        'type': value['type'],
    };
}

