/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface GetWorkspaceFolders200ResponseAllOfDataInner
 */
export interface GetWorkspaceFolders200ResponseAllOfDataInner {
    /**
     * The folder's unique identifier.
     * @type {number}
     * @memberof GetWorkspaceFolders200ResponseAllOfDataInner
     */
    id?: number;
    /**
     * The folder's name.
     * @type {string}
     * @memberof GetWorkspaceFolders200ResponseAllOfDataInner
     */
    name?: string;
    /**
     * URL to the folder in Smartsheet.
     * @type {string}
     * @memberof GetWorkspaceFolders200ResponseAllOfDataInner
     */
    permalink?: string;
}

/**
 * Check if a given object implements the GetWorkspaceFolders200ResponseAllOfDataInner interface.
 */
export function instanceOfGetWorkspaceFolders200ResponseAllOfDataInner(value: object): value is GetWorkspaceFolders200ResponseAllOfDataInner {
    return true;
}

export function GetWorkspaceFolders200ResponseAllOfDataInnerFromJSON(json: any): GetWorkspaceFolders200ResponseAllOfDataInner {
    return GetWorkspaceFolders200ResponseAllOfDataInnerFromJSONTyped(json, false);
}

export function GetWorkspaceFolders200ResponseAllOfDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceFolders200ResponseAllOfDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'permalink': json['permalink'] == null ? undefined : json['permalink'],
    };
}

export function GetWorkspaceFolders200ResponseAllOfDataInnerToJSON(json: any): GetWorkspaceFolders200ResponseAllOfDataInner {
    return GetWorkspaceFolders200ResponseAllOfDataInnerToJSONTyped(json, false);
}

export function GetWorkspaceFolders200ResponseAllOfDataInnerToJSONTyped(value?: GetWorkspaceFolders200ResponseAllOfDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'permalink': value['permalink'],
    };
}

