/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Updates group properties, including name, description, and owner.
 * @export
 * @interface GroupUpdate
 */
export interface GroupUpdate {
    /**
     * name (Optional)
     * 
     * Must be unique within the organization account.
     * 
     * @type {string}
     * @memberof GroupUpdate
     */
    name?: string;
    /**
     * Description (optional).
     * @type {string}
     * @memberof GroupUpdate
     */
    description?: string;
    /**
     * ownerId (optional)
     * 
     * Id of an admin user to whom the group ownership is transferred.
     * 
     * @type {number}
     * @memberof GroupUpdate
     */
    ownerId?: number;
}

/**
 * Check if a given object implements the GroupUpdate interface.
 */
export function instanceOfGroupUpdate(value: object): value is GroupUpdate {
    return true;
}

export function GroupUpdateFromJSON(json: any): GroupUpdate {
    return GroupUpdateFromJSONTyped(json, false);
}

export function GroupUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
    };
}

export function GroupUpdateToJSON(json: any): GroupUpdate {
    return GroupUpdateToJSONTyped(json, false);
}

export function GroupUpdateToJSONTyped(value?: GroupUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'ownerId': value['ownerId'],
    };
}

