/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SheetList } from './SheetList';
import {
    SheetListFromJSON,
    SheetListFromJSONTyped,
    SheetListToJSON,
    SheetListToJSONTyped,
} from './SheetList';

/**
 * 
 * @export
 * @interface ListOrgSheets200Response
 */
export interface ListOrgSheets200Response {
    /**
     * The current page in the full result set that the data array represents. NOTE when a page number greater than totalPages is requested, the last page is instead returned.
     * @type {number}
     * @memberof ListOrgSheets200Response
     */
    readonly pageNumber?: number;
    /**
     * The number of items in a page. Omitted if there is no limit to page size (and hence, all results are included). Unless otherwise specified, this defaults to 100 for most endpoints.
     * @type {number}
     * @memberof ListOrgSheets200Response
     */
    readonly pageSize?: number | null;
    /**
     * If the data field value is not empty, returns a static value of -1. When you reach the first empty page after the end of the result set, then all four fields are set with a static value of “0”.
     * @type {number}
     * @memberof ListOrgSheets200Response
     */
    readonly totalPages?: number;
    /**
     * If the data field value is not empty, returns a static value of -1. When you reach the first empty page after the end of the result set, then all four fields are set with a static value of “0”.
     * @type {number}
     * @memberof ListOrgSheets200Response
     */
    readonly totalCount?: number;
    /**
     * List of Sheets
     * @type {Array<SheetList>}
     * @memberof ListOrgSheets200Response
     */
    data?: Array<SheetList>;
}

/**
 * Check if a given object implements the ListOrgSheets200Response interface.
 */
export function instanceOfListOrgSheets200Response(value: object): value is ListOrgSheets200Response {
    return true;
}

export function ListOrgSheets200ResponseFromJSON(json: any): ListOrgSheets200Response {
    return ListOrgSheets200ResponseFromJSONTyped(json, false);
}

export function ListOrgSheets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrgSheets200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SheetListFromJSON)),
    };
}

export function ListOrgSheets200ResponseToJSON(json: any): ListOrgSheets200Response {
    return ListOrgSheets200ResponseToJSONTyped(json, false);
}

export function ListOrgSheets200ResponseToJSONTyped(value?: Omit<ListOrgSheets200Response, 'pageNumber'|'pageSize'|'totalPages'|'totalCount'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SheetListToJSON)),
    };
}

