/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Recipient } from './Recipient';
import {
    RecipientFromJSON,
    RecipientFromJSONTyped,
    RecipientToJSON,
    RecipientToJSONTyped,
} from './Recipient';

/**
 * 
 * @export
 * @interface MultiRowEmail
 */
export interface MultiRowEmail {
    /**
     * The Ids of rows to be included.
     * @type {Array<number>}
     * @memberof MultiRowEmail
     */
    rowIds?: Array<number>;
    /**
     * The Id of the columns to be included.
     * @type {Array<number>}
     * @memberof MultiRowEmail
     */
    columnIds?: Array<number>;
    /**
     * Indicates whether to include attachments in the email.
     * @type {boolean}
     * @memberof MultiRowEmail
     */
    includeAttachments?: boolean;
    /**
     * Indicates whether to include discussions in the email.
     * @type {boolean}
     * @memberof MultiRowEmail
     */
    includeDiscussions?: boolean;
    /**
     * One of the following values: **HORIZONTAL** or **VERTICAL**. Optional, defaults to **HORIZONTAL** when multiple rows are being sent and to **VERTICAL** when a single row is being sent. **HORIZONTAL** formats the rows being sent as a grid, whereas **VERTICAL** formats the rows being sent as separate cards.
     * 
     * @type {boolean}
     * @memberof MultiRowEmail
     */
    layout?: boolean;
    /**
     * Indicates whether to send a copy of the email to the sender.
     * @type {boolean}
     * @memberof MultiRowEmail
     */
    ccMe?: boolean;
    /**
     * The message of the email.
     * @type {string}
     * @memberof MultiRowEmail
     */
    message?: string;
    /**
     * Array of recipients.
     * @type {Array<Recipient>}
     * @memberof MultiRowEmail
     */
    sendTo?: Array<Recipient>;
    /**
     * The subject of the email.
     * @type {string}
     * @memberof MultiRowEmail
     */
    subject?: string;
}

/**
 * Check if a given object implements the MultiRowEmail interface.
 */
export function instanceOfMultiRowEmail(value: object): value is MultiRowEmail {
    return true;
}

export function MultiRowEmailFromJSON(json: any): MultiRowEmail {
    return MultiRowEmailFromJSONTyped(json, false);
}

export function MultiRowEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiRowEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'rowIds': json['rowIds'] == null ? undefined : json['rowIds'],
        'columnIds': json['columnIds'] == null ? undefined : json['columnIds'],
        'includeAttachments': json['includeAttachments'] == null ? undefined : json['includeAttachments'],
        'includeDiscussions': json['includeDiscussions'] == null ? undefined : json['includeDiscussions'],
        'layout': json['layout'] == null ? undefined : json['layout'],
        'ccMe': json['ccMe'] == null ? undefined : json['ccMe'],
        'message': json['message'] == null ? undefined : json['message'],
        'sendTo': json['sendTo'] == null ? undefined : ((json['sendTo'] as Array<any>).map(RecipientFromJSON)),
        'subject': json['subject'] == null ? undefined : json['subject'],
    };
}

export function MultiRowEmailToJSON(json: any): MultiRowEmail {
    return MultiRowEmailToJSONTyped(json, false);
}

export function MultiRowEmailToJSONTyped(value?: MultiRowEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rowIds': value['rowIds'],
        'columnIds': value['columnIds'],
        'includeAttachments': value['includeAttachments'],
        'includeDiscussions': value['includeDiscussions'],
        'layout': value['layout'],
        'ccMe': value['ccMe'],
        'message': value['message'],
        'sendTo': value['sendTo'] == null ? undefined : ((value['sendTo'] as Array<any>).map(RecipientToJSON)),
        'subject': value['subject'],
    };
}

