/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AddRowsObject } from './AddRowsObject';
import {
    AddRowsObjectFromJSON,
    AddRowsObjectFromJSONTyped,
    AddRowsObjectToJSON,
    AddRowsObjectToJSONTyped,
} from './AddRowsObject';

/**
 * 
 * @export
 * @interface RowsAddToSheet200Response
 */
export interface RowsAddToSheet200Response {
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof RowsAddToSheet200Response
     */
    message?: RowsAddToSheet200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof RowsAddToSheet200Response
     */
    resultCode?: RowsAddToSheet200ResponseResultCodeEnum;
    /**
     * 
     * @type {Array<AddRowsObject>}
     * @memberof RowsAddToSheet200Response
     */
    result?: Array<AddRowsObject>;
}


/**
 * @export
 */
export const RowsAddToSheet200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type RowsAddToSheet200ResponseMessageEnum = typeof RowsAddToSheet200ResponseMessageEnum[keyof typeof RowsAddToSheet200ResponseMessageEnum];

/**
 * @export
 */
export const RowsAddToSheet200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type RowsAddToSheet200ResponseResultCodeEnum = typeof RowsAddToSheet200ResponseResultCodeEnum[keyof typeof RowsAddToSheet200ResponseResultCodeEnum];


/**
 * Check if a given object implements the RowsAddToSheet200Response interface.
 */
export function instanceOfRowsAddToSheet200Response(value: object): value is RowsAddToSheet200Response {
    return true;
}

export function RowsAddToSheet200ResponseFromJSON(json: any): RowsAddToSheet200Response {
    return RowsAddToSheet200ResponseFromJSONTyped(json, false);
}

export function RowsAddToSheet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RowsAddToSheet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(AddRowsObjectFromJSON)),
    };
}

export function RowsAddToSheet200ResponseToJSON(json: any): RowsAddToSheet200Response {
    return RowsAddToSheet200ResponseToJSONTyped(json, false);
}

export function RowsAddToSheet200ResponseToJSONTyped(value?: RowsAddToSheet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(AddRowsObjectToJSON)),
    };
}

