/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Timestamp } from './Timestamp';
import {
    TimestampFromJSON,
    TimestampFromJSONTyped,
    TimestampToJSON,
    TimestampToJSONTyped,
} from './Timestamp';
import type { AccessLevel } from './AccessLevel';
import {
    AccessLevelFromJSON,
    AccessLevelFromJSONTyped,
    AccessLevelToJSON,
    AccessLevelToJSONTyped,
} from './AccessLevel';
import type { Source } from './Source';
import {
    SourceFromJSON,
    SourceFromJSONTyped,
    SourceToJSON,
    SourceToJSONTyped,
} from './Source';

/**
 * 
 * @export
 * @interface SchemasSheet
 */
export interface SchemasSheet {
    /**
     * Sheet Id.
     * @type {number}
     * @memberof SchemasSheet
     */
    id?: number;
    /**
     * 
     * @type {AccessLevel}
     * @memberof SchemasSheet
     */
    accessLevel?: AccessLevel;
    /**
     * 
     * @type {Timestamp}
     * @memberof SchemasSheet
     */
    createdAt?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof SchemasSheet
     */
    modifiedAt?: Timestamp;
    /**
     * Sheet name.
     * @type {string}
     * @memberof SchemasSheet
     */
    name?: string;
    /**
     * URL that represents a direct link to the sheet in Smartsheet.
     * @type {string}
     * @memberof SchemasSheet
     */
    permalink?: string;
    /**
     * A number that is incremented every time a sheet is modified.
     * @type {number}
     * @memberof SchemasSheet
     */
    version?: number;
    /**
     * 
     * @type {Source}
     * @memberof SchemasSheet
     */
    source?: Source;
}



/**
 * Check if a given object implements the SchemasSheet interface.
 */
export function instanceOfSchemasSheet(value: object): value is SchemasSheet {
    return true;
}

export function SchemasSheetFromJSON(json: any): SchemasSheet {
    return SchemasSheetFromJSONTyped(json, false);
}

export function SchemasSheetFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemasSheet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'accessLevel': json['accessLevel'] == null ? undefined : AccessLevelFromJSON(json['accessLevel']),
        'createdAt': json['createdAt'] == null ? undefined : TimestampFromJSON(json['createdAt']),
        'modifiedAt': json['modifiedAt'] == null ? undefined : TimestampFromJSON(json['modifiedAt']),
        'name': json['name'] == null ? undefined : json['name'],
        'permalink': json['permalink'] == null ? undefined : json['permalink'],
        'version': json['version'] == null ? undefined : json['version'],
        'source': json['source'] == null ? undefined : SourceFromJSON(json['source']),
    };
}

export function SchemasSheetToJSON(json: any): SchemasSheet {
    return SchemasSheetToJSONTyped(json, false);
}

export function SchemasSheetToJSONTyped(value?: SchemasSheet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'accessLevel': AccessLevelToJSON(value['accessLevel']),
        'createdAt': TimestampToJSON(value['createdAt']),
        'modifiedAt': TimestampToJSON(value['modifiedAt']),
        'name': value['name'],
        'permalink': value['permalink'],
        'version': value['version'],
        'source': SourceToJSON(value['source']),
    };
}

