/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Updates User for the following attributes:
 * 
 * * **admin** (required).
 * * **licensedSheetCreator** (required).
 * * **firstName** (optional).
 * * **groupAdmin** (optional).
 * * **lastName** (optional).
 * * **resourceViewer** (optional).
 * 
 * @export
 * @interface UserUpdate
 */
export interface UserUpdate {
    /**
     * Indicates whether the user is a system admin (can manage user accounts and organization account).
     * @type {boolean}
     * @memberof UserUpdate
     */
    admin?: boolean;
    /**
     * Indicates whether the user is a licensed user (can create and own sheets).
     * @type {boolean}
     * @memberof UserUpdate
     */
    licensedSheetCreator?: boolean;
    /**
     * User's first name.
     * @type {string}
     * @memberof UserUpdate
     */
    firstName?: string;
    /**
     * User's last name.
     * @type {string}
     * @memberof UserUpdate
     */
    lastName?: string;
    /**
     * Indicates whether the user is a group admin (can create and edit groups).
     * @type {boolean}
     * @memberof UserUpdate
     */
    groupAdmin?: boolean;
    /**
     * Indicates whether the user is a resource viewer (can access resource views).
     * @type {boolean}
     * @memberof UserUpdate
     */
    resourceViewer?: boolean;
}

/**
 * Check if a given object implements the UserUpdate interface.
 */
export function instanceOfUserUpdate(value: object): value is UserUpdate {
    return true;
}

export function UserUpdateFromJSON(json: any): UserUpdate {
    return UserUpdateFromJSONTyped(json, false);
}

export function UserUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'admin': json['admin'] == null ? undefined : json['admin'],
        'licensedSheetCreator': json['licensedSheetCreator'] == null ? undefined : json['licensedSheetCreator'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'groupAdmin': json['groupAdmin'] == null ? undefined : json['groupAdmin'],
        'resourceViewer': json['resourceViewer'] == null ? undefined : json['resourceViewer'],
    };
}

export function UserUpdateToJSON(json: any): UserUpdate {
    return UserUpdateToJSONTyped(json, false);
}

export function UserUpdateToJSONTyped(value?: UserUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'admin': value['admin'],
        'licensedSheetCreator': value['licensedSheetCreator'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'groupAdmin': value['groupAdmin'],
        'resourceViewer': value['resourceViewer'],
    };
}

