/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WidgetChartGridLine
 */
export interface WidgetChartGridLine {
    /**
     * 
     * @type {string}
     * @memberof WidgetChartGridLine
     */
    lineStyle?: WidgetChartGridLineLineStyleEnum;
}


/**
 * @export
 */
export const WidgetChartGridLineLineStyleEnum = {
    Solid: 'SOLID'
} as const;
export type WidgetChartGridLineLineStyleEnum = typeof WidgetChartGridLineLineStyleEnum[keyof typeof WidgetChartGridLineLineStyleEnum];


/**
 * Check if a given object implements the WidgetChartGridLine interface.
 */
export function instanceOfWidgetChartGridLine(value: object): value is WidgetChartGridLine {
    return true;
}

export function WidgetChartGridLineFromJSON(json: any): WidgetChartGridLine {
    return WidgetChartGridLineFromJSONTyped(json, false);
}

export function WidgetChartGridLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetChartGridLine {
    if (json == null) {
        return json;
    }
    return {
        
        'lineStyle': json['lineStyle'] == null ? undefined : json['lineStyle'],
    };
}

export function WidgetChartGridLineToJSON(json: any): WidgetChartGridLine {
    return WidgetChartGridLineToJSONTyped(json, false);
}

export function WidgetChartGridLineToJSONTyped(value?: WidgetChartGridLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lineStyle': value['lineStyle'],
    };
}

