/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Favorite } from './Favorite';
import {
    instanceOfFavorite,
    FavoriteFromJSON,
    FavoriteFromJSONTyped,
    FavoriteToJSON,
} from './Favorite';

/**
 * @type AddFavoriteRequest
 * 
 * @export
 */
export type AddFavoriteRequest = Array<Favorite> | Favorite;

export function AddFavoriteRequestFromJSON(json: any): AddFavoriteRequest {
    return AddFavoriteRequestFromJSONTyped(json, false);
}

export function AddFavoriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddFavoriteRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfFavorite(json)) {
        return FavoriteFromJSONTyped(json, true);
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfFavorite(item))) {
                return json.map(value => FavoriteFromJSONTyped(value, true));
            }
        }
        return json;
    }

    return {} as any;
}

export function AddFavoriteRequestToJSON(json: any): any {
    return AddFavoriteRequestToJSONTyped(json, false);
}

export function AddFavoriteRequestToJSONTyped(value?: AddFavoriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfFavorite(value)) {
        return FavoriteToJSON(value as Favorite);
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfFavorite(item))) {
                return value.map(value => FavoriteToJSON(value as Favorite));
            }
        }
        return value;
    }

    return {};
}

