/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object that describes how the the System Column type of "AUTO_NUMBER" is auto-generated.
 * @export
 * @interface AutoNumberFormat
 */
export interface AutoNumberFormat {
    /**
     * Indicates zero-padding. Must be between 0 and 10 "0" (zero) characters.
     * @type {string}
     * @memberof AutoNumberFormat
     */
    fill?: string;
    /**
     * The prefix. Can include the date tokens:
     *   * {DD}
     *   * {MM}
     *   * {YY}
     *   * {YYYY}
     * 
     * @type {string}
     * @memberof AutoNumberFormat
     */
    prefix?: string;
    /**
     * The starting number for the auto-id.
     * @type {number}
     * @memberof AutoNumberFormat
     */
    startingNumber?: number;
    /**
     * The suffix. Can include the date tokens:
     *   * {DD}
     *   * {MM}
     *   * {YY}
     *   * {YYYY}
     * 
     * @type {string}
     * @memberof AutoNumberFormat
     */
    suffix?: string;
}

/**
 * Check if a given object implements the AutoNumberFormat interface.
 */
export function instanceOfAutoNumberFormat(value: object): value is AutoNumberFormat {
    return true;
}

export function AutoNumberFormatFromJSON(json: any): AutoNumberFormat {
    return AutoNumberFormatFromJSONTyped(json, false);
}

export function AutoNumberFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoNumberFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'fill': json['fill'] == null ? undefined : json['fill'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'startingNumber': json['startingNumber'] == null ? undefined : json['startingNumber'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
    };
}

export function AutoNumberFormatToJSON(json: any): AutoNumberFormat {
    return AutoNumberFormatToJSONTyped(json, false);
}

export function AutoNumberFormatToJSONTyped(value?: AutoNumberFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fill': value['fill'],
        'prefix': value['prefix'],
        'startingNumber': value['startingNumber'],
        'suffix': value['suffix'],
    };
}

