/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type CellDataItemObjectValue
 * The type of data returned depends on the cell type and the data in the cell.
 * @export
 */
export type CellDataItemObjectValue = boolean | number | string;

export function CellDataItemObjectValueFromJSON(json: any): CellDataItemObjectValue {
    return CellDataItemObjectValueFromJSONTyped(json, false);
}

export function CellDataItemObjectValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CellDataItemObjectValue {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function CellDataItemObjectValueToJSON(json: any): any {
    return CellDataItemObjectValueToJSONTyped(json, false);
}

export function CellDataItemObjectValueToJSONTyped(value?: CellDataItemObjectValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

