/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ChartTooltipStyle
 */
export interface ChartTooltipStyle {
    /**
     * 
     * @type {string}
     * @memberof ChartTooltipStyle
     */
    labelType?: ChartTooltipStyleLabelTypeEnum;
}


/**
 * @export
 */
export const ChartTooltipStyleLabelTypeEnum = {
    None: 'NONE',
    Percent: 'PERCENT',
    XSeriesY: 'X_SERIES_Y',
    XYPercent: 'X_Y_PERCENT',
    Y: 'Y',
    YPercent: 'Y_PERCENT'
} as const;
export type ChartTooltipStyleLabelTypeEnum = typeof ChartTooltipStyleLabelTypeEnum[keyof typeof ChartTooltipStyleLabelTypeEnum];


/**
 * Check if a given object implements the ChartTooltipStyle interface.
 */
export function instanceOfChartTooltipStyle(value: object): value is ChartTooltipStyle {
    return true;
}

export function ChartTooltipStyleFromJSON(json: any): ChartTooltipStyle {
    return ChartTooltipStyleFromJSONTyped(json, false);
}

export function ChartTooltipStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartTooltipStyle {
    if (json == null) {
        return json;
    }
    return {
        
        'labelType': json['labelType'] == null ? undefined : json['labelType'],
    };
}

export function ChartTooltipStyleToJSON(json: any): ChartTooltipStyle {
    return ChartTooltipStyleToJSONTyped(json, false);
}

export function ChartTooltipStyleToJSONTyped(value?: ChartTooltipStyle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labelType': value['labelType'],
    };
}

