/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AccessLevel } from './AccessLevel';
import {
    AccessLevelFromJSON,
    AccessLevelFromJSONTyped,
    AccessLevelToJSON,
    AccessLevelToJSONTyped,
} from './AccessLevel';

/**
 * 
 * @export
 * @interface ComponentsSchemasSheet
 */
export interface ComponentsSchemasSheet {
    /**
     * Sheet Id.
     * @type {number}
     * @memberof ComponentsSchemasSheet
     */
    id?: number;
    /**
     * 
     * @type {AccessLevel}
     * @memberof ComponentsSchemasSheet
     */
    accessLevel?: AccessLevel;
    /**
     * Sheet name.
     * @type {string}
     * @memberof ComponentsSchemasSheet
     */
    name?: string;
    /**
     * URL that represents a direct link to the sheet in Smartsheet.
     * @type {string}
     * @memberof ComponentsSchemasSheet
     */
    permalink?: string;
}



/**
 * Check if a given object implements the ComponentsSchemasSheet interface.
 */
export function instanceOfComponentsSchemasSheet(value: object): value is ComponentsSchemasSheet {
    return true;
}

export function ComponentsSchemasSheetFromJSON(json: any): ComponentsSchemasSheet {
    return ComponentsSchemasSheetFromJSONTyped(json, false);
}

export function ComponentsSchemasSheetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentsSchemasSheet {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'accessLevel': json['accessLevel'] == null ? undefined : AccessLevelFromJSON(json['accessLevel']),
        'name': json['name'] == null ? undefined : json['name'],
        'permalink': json['permalink'] == null ? undefined : json['permalink'],
    };
}

export function ComponentsSchemasSheetToJSON(json: any): ComponentsSchemasSheet {
    return ComponentsSchemasSheetToJSONTyped(json, false);
}

export function ComponentsSchemasSheetToJSONTyped(value?: ComponentsSchemasSheet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'accessLevel': AccessLevelToJSON(value['accessLevel']),
        'name': value['name'],
        'permalink': value['permalink'],
    };
}

