/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RowMapping } from './RowMapping';
import {
    RowMappingFromJSON,
    RowMappingFromJSONTyped,
    RowMappingToJSON,
    RowMappingToJSONTyped,
} from './RowMapping';

/**
 * 
 * @export
 * @interface CopyOrMoveRowResult
 */
export interface CopyOrMoveRowResult {
    /**
     * The Id of the destination sheet.
     * @type {number}
     * @memberof CopyOrMoveRowResult
     */
    destinationSheetId?: number;
    /**
     * Array of rowMapping objects.
     * @type {Array<RowMapping>}
     * @memberof CopyOrMoveRowResult
     */
    rowMappings?: Array<RowMapping>;
}

/**
 * Check if a given object implements the CopyOrMoveRowResult interface.
 */
export function instanceOfCopyOrMoveRowResult(value: object): value is CopyOrMoveRowResult {
    return true;
}

export function CopyOrMoveRowResultFromJSON(json: any): CopyOrMoveRowResult {
    return CopyOrMoveRowResultFromJSONTyped(json, false);
}

export function CopyOrMoveRowResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopyOrMoveRowResult {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationSheetId': json['destinationSheetId'] == null ? undefined : json['destinationSheetId'],
        'rowMappings': json['rowMappings'] == null ? undefined : ((json['rowMappings'] as Array<any>).map(RowMappingFromJSON)),
    };
}

export function CopyOrMoveRowResultToJSON(json: any): CopyOrMoveRowResult {
    return CopyOrMoveRowResultToJSONTyped(json, false);
}

export function CopyOrMoveRowResultToJSONTyped(value?: CopyOrMoveRowResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationSheetId': value['destinationSheetId'],
        'rowMappings': value['rowMappings'] == null ? undefined : ((value['rowMappings'] as Array<any>).map(RowMappingToJSON)),
    };
}

