/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SheetCreated } from './SheetCreated';
import {
    instanceOfSheetCreated,
    SheetCreatedFromJSON,
    SheetCreatedFromJSONTyped,
    SheetCreatedToJSON,
} from './SheetCreated';
import type { SheetCreatedFromTemplate } from './SheetCreatedFromTemplate';
import {
    instanceOfSheetCreatedFromTemplate,
    SheetCreatedFromTemplateFromJSON,
    SheetCreatedFromTemplateFromJSONTyped,
    SheetCreatedFromTemplateToJSON,
} from './SheetCreatedFromTemplate';

/**
 * @type CreateSheetInFolder200ResponseAllOfResult
 * 
 * @export
 */
export type CreateSheetInFolder200ResponseAllOfResult = SheetCreated | SheetCreatedFromTemplate;

export function CreateSheetInFolder200ResponseAllOfResultFromJSON(json: any): CreateSheetInFolder200ResponseAllOfResult {
    return CreateSheetInFolder200ResponseAllOfResultFromJSONTyped(json, false);
}

export function CreateSheetInFolder200ResponseAllOfResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSheetInFolder200ResponseAllOfResult {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfSheetCreated(json)) {
        return SheetCreatedFromJSONTyped(json, true);
    }
    if (instanceOfSheetCreatedFromTemplate(json)) {
        return SheetCreatedFromTemplateFromJSONTyped(json, true);
    }

    return {} as any;
}

export function CreateSheetInFolder200ResponseAllOfResultToJSON(json: any): any {
    return CreateSheetInFolder200ResponseAllOfResultToJSONTyped(json, false);
}

export function CreateSheetInFolder200ResponseAllOfResultToJSONTyped(value?: CreateSheetInFolder200ResponseAllOfResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfSheetCreated(value)) {
        return SheetCreatedToJSON(value as SheetCreated);
    }
    if (instanceOfSheetCreatedFromTemplate(value)) {
        return SheetCreatedFromTemplateToJSON(value as SheetCreatedFromTemplate);
    }

    return {};
}

