/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * CrossSheetReference object to create with specified cell range.
 * @export
 * @interface CrossSheetReferenceRequestWithColumnAndRowIds
 */
export interface CrossSheetReferenceRequestWithColumnAndRowIds {
    /**
     * Sheet Id of source sheet.
     * @type {number}
     * @memberof CrossSheetReferenceRequestWithColumnAndRowIds
     */
    sourceSheetId?: number;
    /**
     * Friendly name of reference. Auto-generated unless specified in Create Cross-sheet References.
     * @type {string}
     * @memberof CrossSheetReferenceRequestWithColumnAndRowIds
     */
    name?: string;
    /**
     * Defines ending edge of range when specifying one or more columns. Must be used with startColumnId. To specify an entire column, omit the startRowId and endRowId parameters.
     * @type {number}
     * @memberof CrossSheetReferenceRequestWithColumnAndRowIds
     */
    endColumnId?: number;
    /**
     * Defines ending edge of range when specifying one or more rows. Must be used with startRowId. To specify an entire row, omit the startColumnId and endColumnId parameters.
     * @type {number}
     * @memberof CrossSheetReferenceRequestWithColumnAndRowIds
     */
    endRowId?: number;
    /**
     * Defines beginning edge of range when specifying one or more columns. Must be used with endColumnId. To specify an entire column, omit the startRowId and endRowId parameters.
     * @type {number}
     * @memberof CrossSheetReferenceRequestWithColumnAndRowIds
     */
    startColumnId?: number;
    /**
     * Defines beginning edge of range when specifying one or more rows. Must be used with endRowId. To specify an entire row, omit the startColumnId and endColumnId parameters.
     * @type {number}
     * @memberof CrossSheetReferenceRequestWithColumnAndRowIds
     */
    startRowId?: number;
}

/**
 * Check if a given object implements the CrossSheetReferenceRequestWithColumnAndRowIds interface.
 */
export function instanceOfCrossSheetReferenceRequestWithColumnAndRowIds(value: object): value is CrossSheetReferenceRequestWithColumnAndRowIds {
    return true;
}

export function CrossSheetReferenceRequestWithColumnAndRowIdsFromJSON(json: any): CrossSheetReferenceRequestWithColumnAndRowIds {
    return CrossSheetReferenceRequestWithColumnAndRowIdsFromJSONTyped(json, false);
}

export function CrossSheetReferenceRequestWithColumnAndRowIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossSheetReferenceRequestWithColumnAndRowIds {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceSheetId': json['sourceSheetId'] == null ? undefined : json['sourceSheetId'],
        'name': json['name'] == null ? undefined : json['name'],
        'endColumnId': json['endColumnId'] == null ? undefined : json['endColumnId'],
        'endRowId': json['endRowId'] == null ? undefined : json['endRowId'],
        'startColumnId': json['startColumnId'] == null ? undefined : json['startColumnId'],
        'startRowId': json['startRowId'] == null ? undefined : json['startRowId'],
    };
}

export function CrossSheetReferenceRequestWithColumnAndRowIdsToJSON(json: any): CrossSheetReferenceRequestWithColumnAndRowIds {
    return CrossSheetReferenceRequestWithColumnAndRowIdsToJSONTyped(json, false);
}

export function CrossSheetReferenceRequestWithColumnAndRowIdsToJSONTyped(value?: CrossSheetReferenceRequestWithColumnAndRowIds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceSheetId': value['sourceSheetId'],
        'name': value['name'],
        'endColumnId': value['endColumnId'],
        'endRowId': value['endRowId'],
        'startColumnId': value['startColumnId'],
        'startRowId': value['startRowId'],
    };
}

