/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Discussion } from './Discussion';
import {
    DiscussionFromJSON,
    DiscussionFromJSONTyped,
    DiscussionToJSON,
    DiscussionToJSONTyped,
} from './Discussion';

/**
 * 
 * @export
 * @interface DiscussionsCreate200Response
 */
export interface DiscussionsCreate200Response {
    /**
     * New version of the sheet. Applicable only for operations which update sheet data.
     * @type {number}
     * @memberof DiscussionsCreate200Response
     */
    version?: number | null;
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof DiscussionsCreate200Response
     */
    message?: DiscussionsCreate200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof DiscussionsCreate200Response
     */
    resultCode?: DiscussionsCreate200ResponseResultCodeEnum;
    /**
     * 
     * @type {Discussion}
     * @memberof DiscussionsCreate200Response
     */
    result?: Discussion;
}


/**
 * @export
 */
export const DiscussionsCreate200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type DiscussionsCreate200ResponseMessageEnum = typeof DiscussionsCreate200ResponseMessageEnum[keyof typeof DiscussionsCreate200ResponseMessageEnum];

/**
 * @export
 */
export const DiscussionsCreate200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type DiscussionsCreate200ResponseResultCodeEnum = typeof DiscussionsCreate200ResponseResultCodeEnum[keyof typeof DiscussionsCreate200ResponseResultCodeEnum];


/**
 * Check if a given object implements the DiscussionsCreate200Response interface.
 */
export function instanceOfDiscussionsCreate200Response(value: object): value is DiscussionsCreate200Response {
    return true;
}

export function DiscussionsCreate200ResponseFromJSON(json: any): DiscussionsCreate200Response {
    return DiscussionsCreate200ResponseFromJSONTyped(json, false);
}

export function DiscussionsCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscussionsCreate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : DiscussionFromJSON(json['result']),
    };
}

export function DiscussionsCreate200ResponseToJSON(json: any): DiscussionsCreate200Response {
    return DiscussionsCreate200ResponseToJSONTyped(json, false);
}

export function DiscussionsCreate200ResponseToJSONTyped(value?: DiscussionsCreate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': DiscussionToJSON(value['result']),
    };
}

