/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommentRequest } from './CommentRequest';
import {
    CommentRequestFromJSON,
    CommentRequestFromJSONTyped,
    CommentRequestToJSON,
    CommentRequestToJSONTyped,
} from './CommentRequest';

/**
 * Discussion.
 * @export
 * @interface DiscussionCreationRequestWithAttachmentDiscussion
 */
export interface DiscussionCreationRequestWithAttachmentDiscussion {
    /**
     * 
     * @type {CommentRequest}
     * @memberof DiscussionCreationRequestWithAttachmentDiscussion
     */
    comment?: CommentRequest;
    /**
     * Title for the attachment. Only used with an attachment.
     * @type {string}
     * @memberof DiscussionCreationRequestWithAttachmentDiscussion
     */
    title?: string;
}

/**
 * Check if a given object implements the DiscussionCreationRequestWithAttachmentDiscussion interface.
 */
export function instanceOfDiscussionCreationRequestWithAttachmentDiscussion(value: object): value is DiscussionCreationRequestWithAttachmentDiscussion {
    return true;
}

export function DiscussionCreationRequestWithAttachmentDiscussionFromJSON(json: any): DiscussionCreationRequestWithAttachmentDiscussion {
    return DiscussionCreationRequestWithAttachmentDiscussionFromJSONTyped(json, false);
}

export function DiscussionCreationRequestWithAttachmentDiscussionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscussionCreationRequestWithAttachmentDiscussion {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : CommentRequestFromJSON(json['comment']),
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function DiscussionCreationRequestWithAttachmentDiscussionToJSON(json: any): DiscussionCreationRequestWithAttachmentDiscussion {
    return DiscussionCreationRequestWithAttachmentDiscussionToJSONTyped(json, false);
}

export function DiscussionCreationRequestWithAttachmentDiscussionToJSONTyped(value?: DiscussionCreationRequestWithAttachmentDiscussion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': CommentRequestToJSON(value['comment']),
        'title': value['title'],
    };
}

