/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface FontFamily
 */
export interface FontFamily {
    /**
     * Name of the font family.
     * @type {string}
     * @memberof FontFamily
     */
    name?: string;
    /**
     * Platform-independent traits of the font family. Contains one of the listed enum values.
     * @type {Array<string>}
     * @memberof FontFamily
     */
    traits?: Array<FontFamilyTraitsEnum>;
}


/**
 * @export
 */
export const FontFamilyTraitsEnum = {
    SansSerif: 'sans-serif',
    Serif: 'serif'
} as const;
export type FontFamilyTraitsEnum = typeof FontFamilyTraitsEnum[keyof typeof FontFamilyTraitsEnum];


/**
 * Check if a given object implements the FontFamily interface.
 */
export function instanceOfFontFamily(value: object): value is FontFamily {
    return true;
}

export function FontFamilyFromJSON(json: any): FontFamily {
    return FontFamilyFromJSONTyped(json, false);
}

export function FontFamilyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FontFamily {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'traits': json['traits'] == null ? undefined : json['traits'],
    };
}

export function FontFamilyToJSON(json: any): FontFamily {
    return FontFamilyToJSONTyped(json, false);
}

export function FontFamilyToJSONTyped(value?: FontFamily | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'traits': value['traits'],
    };
}

