/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BulkItemFailure } from './BulkItemFailure';
import {
    BulkItemFailureFromJSON,
    BulkItemFailureFromJSONTyped,
    BulkItemFailureToJSON,
    BulkItemFailureToJSONTyped,
} from './BulkItemFailure';

/**
 * 
 * @export
 * @interface ItemResult
 */
export interface ItemResult {
    /**
     * Array of BulkItemFailure objects which represents the items that failed to be added or updated. See [Bulk operations > Partial success](/api/smartsheet/guides/advanced-topics/scalability-options) for more information. Applicable only for bulk operations that support partial success.
     * @type {Array<BulkItemFailure>}
     * @memberof ItemResult
     */
    failedItems?: Array<BulkItemFailure> | null;
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof ItemResult
     */
    message?: ItemResultMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof ItemResult
     */
    resultCode?: ItemResultResultCodeEnum;
}


/**
 * @export
 */
export const ItemResultMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type ItemResultMessageEnum = typeof ItemResultMessageEnum[keyof typeof ItemResultMessageEnum];

/**
 * @export
 */
export const ItemResultResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type ItemResultResultCodeEnum = typeof ItemResultResultCodeEnum[keyof typeof ItemResultResultCodeEnum];


/**
 * Check if a given object implements the ItemResult interface.
 */
export function instanceOfItemResult(value: object): value is ItemResult {
    return true;
}

export function ItemResultFromJSON(json: any): ItemResult {
    return ItemResultFromJSONTyped(json, false);
}

export function ItemResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemResult {
    if (json == null) {
        return json;
    }
    return {
        
        'failedItems': json['failedItems'] == null ? undefined : ((json['failedItems'] as Array<any>).map(BulkItemFailureFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
    };
}

export function ItemResultToJSON(json: any): ItemResult {
    return ItemResultToJSONTyped(json, false);
}

export function ItemResultToJSONTyped(value?: ItemResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failedItems': value['failedItems'] == null ? undefined : ((value['failedItems'] as Array<any>).map(BulkItemFailureToJSON)),
        'message': value['message'],
        'resultCode': value['resultCode'],
    };
}

