/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProofRequest } from './ProofRequest';
import {
    ProofRequestFromJSON,
    ProofRequestFromJSONTyped,
    ProofRequestToJSON,
    ProofRequestToJSONTyped,
} from './ProofRequest';

/**
 * 
 * @export
 * @interface ProofsCreateProofRequests200Response
 */
export interface ProofsCreateProofRequests200Response {
    /**
     * Message that indicates the outcome of the request. (One of SUCCESS or PARTIAL_SUCCESS.)
     * @type {string}
     * @memberof ProofsCreateProofRequests200Response
     */
    message?: ProofsCreateProofRequests200ResponseMessageEnum;
    /**
     * * '0' Success
     * * '3' Partial Success of Bulk Operation
     * @type {number}
     * @memberof ProofsCreateProofRequests200Response
     */
    resultCode?: ProofsCreateProofRequests200ResponseResultCodeEnum;
    /**
     * 
     * @type {ProofRequest}
     * @memberof ProofsCreateProofRequests200Response
     */
    result?: ProofRequest;
}


/**
 * @export
 */
export const ProofsCreateProofRequests200ResponseMessageEnum = {
    PartialSuccess: 'PARTIAL_SUCCESS',
    Success: 'SUCCESS'
} as const;
export type ProofsCreateProofRequests200ResponseMessageEnum = typeof ProofsCreateProofRequests200ResponseMessageEnum[keyof typeof ProofsCreateProofRequests200ResponseMessageEnum];

/**
 * @export
 */
export const ProofsCreateProofRequests200ResponseResultCodeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3
} as const;
export type ProofsCreateProofRequests200ResponseResultCodeEnum = typeof ProofsCreateProofRequests200ResponseResultCodeEnum[keyof typeof ProofsCreateProofRequests200ResponseResultCodeEnum];


/**
 * Check if a given object implements the ProofsCreateProofRequests200Response interface.
 */
export function instanceOfProofsCreateProofRequests200Response(value: object): value is ProofsCreateProofRequests200Response {
    return true;
}

export function ProofsCreateProofRequests200ResponseFromJSON(json: any): ProofsCreateProofRequests200Response {
    return ProofsCreateProofRequests200ResponseFromJSONTyped(json, false);
}

export function ProofsCreateProofRequests200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofsCreateProofRequests200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'resultCode': json['resultCode'] == null ? undefined : json['resultCode'],
        'result': json['result'] == null ? undefined : ProofRequestFromJSON(json['result']),
    };
}

export function ProofsCreateProofRequests200ResponseToJSON(json: any): ProofsCreateProofRequests200Response {
    return ProofsCreateProofRequests200ResponseToJSONTyped(json, false);
}

export function ProofsCreateProofRequests200ResponseToJSONTyped(value?: ProofsCreateProofRequests200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'resultCode': value['resultCode'],
        'result': ProofRequestToJSON(value['result']),
    };
}

