/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates which view the user has set for a read-write, default view of the published sheet. Must be one of the listed enum values.
 * 
 * @export
 */
export const ReadWriteDefaultView = {
    Calendar: 'CALENDAR',
    Card: 'CARD',
    Grid: 'GRID'
} as const;
export type ReadWriteDefaultView = typeof ReadWriteDefaultView[keyof typeof ReadWriteDefaultView];


export function instanceOfReadWriteDefaultView(value: any): boolean {
    for (const key in ReadWriteDefaultView) {
        if (Object.prototype.hasOwnProperty.call(ReadWriteDefaultView, key)) {
            if (ReadWriteDefaultView[key as keyof typeof ReadWriteDefaultView] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReadWriteDefaultViewFromJSON(json: any): ReadWriteDefaultView {
    return ReadWriteDefaultViewFromJSONTyped(json, false);
}

export function ReadWriteDefaultViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadWriteDefaultView {
    return json as ReadWriteDefaultView;
}

export function ReadWriteDefaultViewToJSON(value?: ReadWriteDefaultView | null): any {
    return value as any;
}

export function ReadWriteDefaultViewToJSONTyped(value: any, ignoreDiscriminator: boolean): ReadWriteDefaultView {
    return value as ReadWriteDefaultView;
}

