/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RecipientGroup } from './RecipientGroup';
import {
    instanceOfRecipientGroup,
    RecipientGroupFromJSON,
    RecipientGroupFromJSONTyped,
    RecipientGroupToJSON,
} from './RecipientGroup';
import type { RecipientIndividual } from './RecipientIndividual';
import {
    instanceOfRecipientIndividual,
    RecipientIndividualFromJSON,
    RecipientIndividualFromJSONTyped,
    RecipientIndividualToJSON,
} from './RecipientIndividual';

/**
 * @type Recipient
 * Specifies the recipient of an email. The recipient may be either an individual or a group. To specify an individual, set the email attribute; to specify a group, set the groupId attribute. Either email and groupId may be set, but not both.
 * 
 * @export
 */
export type Recipient = RecipientGroup | RecipientIndividual;

export function RecipientFromJSON(json: any): Recipient {
    return RecipientFromJSONTyped(json, false);
}

export function RecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recipient {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfRecipientGroup(json)) {
        return RecipientGroupFromJSONTyped(json, true);
    }
    if (instanceOfRecipientIndividual(json)) {
        return RecipientIndividualFromJSONTyped(json, true);
    }

    return {} as any;
}

export function RecipientToJSON(json: any): any {
    return RecipientToJSONTyped(json, false);
}

export function RecipientToJSONTyped(value?: Recipient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfRecipientGroup(value)) {
        return RecipientGroupToJSON(value as RecipientGroup);
    }
    if (instanceOfRecipientIndividual(value)) {
        return RecipientIndividualToJSON(value as RecipientIndividual);
    }

    return {};
}

