/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Defines a block of cells in a sheet.
 * @export
 * @interface SelectionRange
 */
export interface SelectionRange {
    /**
     * Defines beginning edge of range when specifying one or more columns.
     * @type {number}
     * @memberof SelectionRange
     */
    sourceColumnId1?: number;
    /**
     * Defines ending edge of range when specifying one or more columns.
     * @type {number}
     * @memberof SelectionRange
     */
    sourceColumnId2?: number;
    /**
     * Defines beginning edge of range when specifying one or more rows.
     * @type {number}
     * @memberof SelectionRange
     */
    sourceRowId1?: number;
    /**
     * Defines ending edge of range when specifying one or more rows.
     * @type {number}
     * @memberof SelectionRange
     */
    sourceRowId2?: number;
}

/**
 * Check if a given object implements the SelectionRange interface.
 */
export function instanceOfSelectionRange(value: object): value is SelectionRange {
    return true;
}

export function SelectionRangeFromJSON(json: any): SelectionRange {
    return SelectionRangeFromJSONTyped(json, false);
}

export function SelectionRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectionRange {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceColumnId1': json['sourceColumnId1'] == null ? undefined : json['sourceColumnId1'],
        'sourceColumnId2': json['sourceColumnId2'] == null ? undefined : json['sourceColumnId2'],
        'sourceRowId1': json['sourceRowId1'] == null ? undefined : json['sourceRowId1'],
        'sourceRowId2': json['sourceRowId2'] == null ? undefined : json['sourceRowId2'],
    };
}

export function SelectionRangeToJSON(json: any): SelectionRange {
    return SelectionRangeToJSONTyped(json, false);
}

export function SelectionRangeToJSONTyped(value?: SelectionRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceColumnId1': value['sourceColumnId1'],
        'sourceColumnId2': value['sourceColumnId2'],
        'sourceRowId1': value['sourceRowId1'],
        'sourceRowId2': value['sourceRowId2'],
    };
}

