/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describes the current user's editing permissions for a specific sheet.
 * @export
 * @interface SheetUserPermissions
 */
export interface SheetUserPermissions {
    /**
     * One of:
     *   * ADMIN: full control over fields.
     *   * READ_DELETE: sheet is owned by an individual account that doesn't have summary capabilities. If a summary exists, the only possible operations are GET and DELETE fields.
     *   * READ_ONLY.
     *   * READ_WRITE: can edit values of existing fields, but not create or delete fields, nor modify field type.
     * 
     * @type {string}
     * @memberof SheetUserPermissions
     */
    summaryPermissions?: SheetUserPermissionsSummaryPermissionsEnum;
}


/**
 * @export
 */
export const SheetUserPermissionsSummaryPermissionsEnum = {
    Admin: 'ADMIN',
    ReadDelete: 'READ_DELETE',
    ReadOnly: 'READ_ONLY',
    ReadWrite: 'READ_WRITE'
} as const;
export type SheetUserPermissionsSummaryPermissionsEnum = typeof SheetUserPermissionsSummaryPermissionsEnum[keyof typeof SheetUserPermissionsSummaryPermissionsEnum];


/**
 * Check if a given object implements the SheetUserPermissions interface.
 */
export function instanceOfSheetUserPermissions(value: object): value is SheetUserPermissions {
    return true;
}

export function SheetUserPermissionsFromJSON(json: any): SheetUserPermissions {
    return SheetUserPermissionsFromJSONTyped(json, false);
}

export function SheetUserPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetUserPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'summaryPermissions': json['summaryPermissions'] == null ? undefined : json['summaryPermissions'],
    };
}

export function SheetUserPermissionsToJSON(json: any): SheetUserPermissions {
    return SheetUserPermissionsToJSONTyped(json, false);
}

export function SheetUserPermissionsToJSONTyped(value?: SheetUserPermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summaryPermissions': value['summaryPermissions'],
    };
}

