/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sheet to create from template.
 * @export
 * @interface SheetToCreateFromTemplate
 */
export interface SheetToCreateFromTemplate {
    /**
     * Template Id from which to create the sheet.
     * @type {number}
     * @memberof SheetToCreateFromTemplate
     */
    fromId?: number;
    /**
     * Sheet name.
     * @type {string}
     * @memberof SheetToCreateFromTemplate
     */
    name?: string;
}

/**
 * Check if a given object implements the SheetToCreateFromTemplate interface.
 */
export function instanceOfSheetToCreateFromTemplate(value: object): value is SheetToCreateFromTemplate {
    return true;
}

export function SheetToCreateFromTemplateFromJSON(json: any): SheetToCreateFromTemplate {
    return SheetToCreateFromTemplateFromJSONTyped(json, false);
}

export function SheetToCreateFromTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SheetToCreateFromTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'fromId': json['fromId'] == null ? undefined : json['fromId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SheetToCreateFromTemplateToJSON(json: any): SheetToCreateFromTemplate {
    return SheetToCreateFromTemplateToJSONTyped(json, false);
}

export function SheetToCreateFromTemplateToJSONTyped(value?: SheetToCreateFromTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromId': value['fromId'],
        'name': value['name'],
    };
}

