/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * StreamResult Object
 * @export
 * @interface StreamResult
 */
export interface StreamResult {
    /**
     * This string should be passed back to the next GET events call to obtain subsequent events.
     * @type {string}
     * @memberof StreamResult
     */
    nextStreamPosition?: string;
    /**
     * True if more results are available. This is typically due to event counts exceeding the maxCount parameter passed in.
     * @type {boolean}
     * @memberof StreamResult
     */
    moreAvailable?: boolean;
}

/**
 * Check if a given object implements the StreamResult interface.
 */
export function instanceOfStreamResult(value: object): value is StreamResult {
    return true;
}

export function StreamResultFromJSON(json: any): StreamResult {
    return StreamResultFromJSONTyped(json, false);
}

export function StreamResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamResult {
    if (json == null) {
        return json;
    }
    return {
        
        'nextStreamPosition': json['nextStreamPosition'] == null ? undefined : json['nextStreamPosition'],
        'moreAvailable': json['moreAvailable'] == null ? undefined : json['moreAvailable'],
    };
}

export function StreamResultToJSON(json: any): StreamResult {
    return StreamResultToJSONTyped(json, false);
}

export function StreamResultToJSONTyped(value?: StreamResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextStreamPosition': value['nextStreamPosition'],
        'moreAvailable': value['moreAvailable'],
    };
}

