/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ObjectValue } from './ObjectValue';
import {
    ObjectValueFromJSON,
    ObjectValueFromJSONTyped,
    ObjectValueToJSON,
    ObjectValueToJSONTyped,
} from './ObjectValue';
import type { ContactOption } from './ContactOption';
import {
    ContactOptionFromJSON,
    ContactOptionFromJSONTyped,
    ContactOptionToJSON,
    ContactOptionToJSONTyped,
} from './ContactOption';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';
import type { Timestamp } from './Timestamp';
import {
    TimestampFromJSON,
    TimestampFromJSONTyped,
    TimestampToJSON,
    TimestampToJSONTyped,
} from './Timestamp';
import type { Hyperlink } from './Hyperlink';
import {
    HyperlinkFromJSON,
    HyperlinkFromJSONTyped,
    HyperlinkToJSON,
    HyperlinkToJSONTyped,
} from './Hyperlink';
import type { MiniUser } from './MiniUser';
import {
    MiniUserFromJSON,
    MiniUserFromJSONTyped,
    MiniUserToJSON,
    MiniUserToJSONTyped,
} from './MiniUser';

/**
 * 
 * @export
 * @interface SummaryField
 */
export interface SummaryField {
    /**
     * SummaryField Id.
     * @type {number}
     * @memberof SummaryField
     */
    id?: number;
    /**
     * Array of ContactOption objects to specify a pre-defined list of values for the column. Column type must be CONTACT_LIST.
     * @type {Array<ContactOption>}
     * @memberof SummaryField
     */
    contactOptions?: Array<ContactOption>;
    /**
     * 
     * @type {Timestamp}
     * @memberof SummaryField
     */
    createdAt?: Timestamp;
    /**
     * User object containing name and email of the creator of this summary field.
     * @type {MiniUser}
     * @memberof SummaryField
     */
    createdBy?: MiniUser;
    /**
     * Visual representation of cell contents, as presented to the user in the UI.
     * @type {string}
     * @memberof SummaryField
     */
    displayValue?: string;
    /**
     * The format descriptor. Only returned if the include query string parameter contains format and this column has a non-default format applied to it.
     * @type {string}
     * @memberof SummaryField
     */
    format?: string;
    /**
     * The formula for a cell, if set.
     * @type {string}
     * @memberof SummaryField
     */
    formula?: string;
    /**
     * 
     * @type {Hyperlink}
     * @memberof SummaryField
     */
    hyperlink?: Hyperlink;
    /**
     * 
     * @type {Image}
     * @memberof SummaryField
     */
    image?: Image;
    /**
     * Field index or position. This number is zero-based.
     * @type {number}
     * @memberof SummaryField
     */
    index?: number;
    /**
     * Indicates whether the field is locked.
     * @type {boolean}
     * @memberof SummaryField
     */
    locked?: boolean;
    /**
     * Indicates whether the field is locked for the requesting user.
     * @type {boolean}
     * @memberof SummaryField
     */
    lockedForUser?: boolean;
    /**
     * 
     * @type {Timestamp}
     * @memberof SummaryField
     */
    modifiedAt?: Timestamp;
    /**
     * User object containing name and email of the user who most recently modified this summary field.
     * @type {MiniUser}
     * @memberof SummaryField
     */
    modifiedBy?: MiniUser;
    /**
     * 
     * @type {ObjectValue}
     * @memberof SummaryField
     */
    objectValue?: ObjectValue;
    /**
     * When applicable for PICKLIST column type. Array of the options available for the field.
     * @type {Array<string>}
     * @memberof SummaryField
     */
    options?: Array<string>;
    /**
     * When applicable for PICKLIST column type.
     * @type {string}
     * @memberof SummaryField
     */
    symbol?: string;
    /**
     * Arbitrary name, must be unique within summary.
     * @type {string}
     * @memberof SummaryField
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SummaryField
     */
    type?: SummaryFieldTypeEnum;
    /**
     * Indicates whether summary field values are restricted to the type.
     * @type {boolean}
     * @memberof SummaryField
     */
    validation?: boolean;
}


/**
 * @export
 */
export const SummaryFieldTypeEnum = {
    AbstractDatetime: 'ABSTRACT_DATETIME',
    Checkbox: 'CHECKBOX',
    ContactList: 'CONTACT_LIST',
    Date: 'DATE',
    Datetime: 'DATETIME',
    Duration: 'DURATION',
    MultiContactList: 'MULTI_CONTACT_LIST',
    MultiPicklist: 'MULTI_PICKLIST',
    Picklist: 'PICKLIST',
    Predecessor: 'PREDECESSOR',
    TextNumber: 'TEXT_NUMBER'
} as const;
export type SummaryFieldTypeEnum = typeof SummaryFieldTypeEnum[keyof typeof SummaryFieldTypeEnum];


/**
 * Check if a given object implements the SummaryField interface.
 */
export function instanceOfSummaryField(value: object): value is SummaryField {
    return true;
}

export function SummaryFieldFromJSON(json: any): SummaryField {
    return SummaryFieldFromJSONTyped(json, false);
}

export function SummaryFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryField {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'contactOptions': json['contactOptions'] == null ? undefined : ((json['contactOptions'] as Array<any>).map(ContactOptionFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : TimestampFromJSON(json['createdAt']),
        'createdBy': json['createdBy'] == null ? undefined : MiniUserFromJSON(json['createdBy']),
        'displayValue': json['displayValue'] == null ? undefined : json['displayValue'],
        'format': json['format'] == null ? undefined : json['format'],
        'formula': json['formula'] == null ? undefined : json['formula'],
        'hyperlink': json['hyperlink'] == null ? undefined : HyperlinkFromJSON(json['hyperlink']),
        'image': json['image'] == null ? undefined : ImageFromJSON(json['image']),
        'index': json['index'] == null ? undefined : json['index'],
        'locked': json['locked'] == null ? undefined : json['locked'],
        'lockedForUser': json['lockedForUser'] == null ? undefined : json['lockedForUser'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : TimestampFromJSON(json['modifiedAt']),
        'modifiedBy': json['modifiedBy'] == null ? undefined : MiniUserFromJSON(json['modifiedBy']),
        'objectValue': json['objectValue'] == null ? undefined : ObjectValueFromJSON(json['objectValue']),
        'options': json['options'] == null ? undefined : json['options'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'validation': json['validation'] == null ? undefined : json['validation'],
    };
}

export function SummaryFieldToJSON(json: any): SummaryField {
    return SummaryFieldToJSONTyped(json, false);
}

export function SummaryFieldToJSONTyped(value?: SummaryField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'contactOptions': value['contactOptions'] == null ? undefined : ((value['contactOptions'] as Array<any>).map(ContactOptionToJSON)),
        'createdAt': TimestampToJSON(value['createdAt']),
        'createdBy': MiniUserToJSON(value['createdBy']),
        'displayValue': value['displayValue'],
        'format': value['format'],
        'formula': value['formula'],
        'hyperlink': HyperlinkToJSON(value['hyperlink']),
        'image': ImageToJSON(value['image']),
        'index': value['index'],
        'locked': value['locked'],
        'lockedForUser': value['lockedForUser'],
        'modifiedAt': TimestampToJSON(value['modifiedAt']),
        'modifiedBy': MiniUserToJSON(value['modifiedBy']),
        'objectValue': ObjectValueToJSON(value['objectValue']),
        'options': value['options'],
        'symbol': value['symbol'],
        'title': value['title'],
        'type': value['type'],
        'validation': value['validation'],
    };
}

