/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Schedule } from './Schedule';
import {
    ScheduleFromJSON,
    ScheduleFromJSONTyped,
    ScheduleToJSON,
    ScheduleToJSONTyped,
} from './Schedule';
import type { Recipient } from './Recipient';
import {
    RecipientFromJSON,
    RecipientFromJSONTyped,
    RecipientToJSON,
    RecipientToJSONTyped,
} from './Recipient';
import type { Timestamp } from './Timestamp';
import {
    TimestampFromJSON,
    TimestampFromJSONTyped,
    TimestampToJSON,
    TimestampToJSONTyped,
} from './Timestamp';
import type { MiniUser } from './MiniUser';
import {
    MiniUserFromJSON,
    MiniUserFromJSONTyped,
    MiniUserToJSON,
    MiniUserToJSONTyped,
} from './MiniUser';

/**
 * 
 * @export
 * @interface UpdateRequest
 */
export interface UpdateRequest {
    /**
     * The Ids of rows to be included.
     * @type {Array<number>}
     * @memberof UpdateRequest
     */
    rowIds?: Array<number>;
    /**
     * The Id of the columns to be included.
     * @type {Array<number>}
     * @memberof UpdateRequest
     */
    columnIds?: Array<number>;
    /**
     * Indicates whether to include attachments in the email.
     * @type {boolean}
     * @memberof UpdateRequest
     */
    includeAttachments?: boolean;
    /**
     * Indicates whether to include discussions in the email.
     * @type {boolean}
     * @memberof UpdateRequest
     */
    includeDiscussions?: boolean;
    /**
     * One of the following values: **HORIZONTAL** or **VERTICAL**. Optional, defaults to **HORIZONTAL** when multiple rows are being sent and to **VERTICAL** when a single row is being sent. **HORIZONTAL** formats the rows being sent as a grid, whereas **VERTICAL** formats the rows being sent as separate cards.
     * 
     * @type {boolean}
     * @memberof UpdateRequest
     */
    layout?: boolean;
    /**
     * Indicates whether to send a copy of the email to the sender.
     * @type {boolean}
     * @memberof UpdateRequest
     */
    ccMe?: boolean;
    /**
     * The message of the email.
     * @type {string}
     * @memberof UpdateRequest
     */
    message?: string;
    /**
     * Array of recipients.
     * @type {Array<Recipient>}
     * @memberof UpdateRequest
     */
    sendTo?: Array<Recipient>;
    /**
     * The subject of the email.
     * @type {string}
     * @memberof UpdateRequest
     */
    subject?: string;
    /**
     * Id of the update request.
     * @type {number}
     * @memberof UpdateRequest
     */
    id?: number;
    /**
     * The date and time for when this request was originally created. Read-only.
     * @type {Timestamp}
     * @memberof UpdateRequest
     */
    createdAt?: Timestamp;
    /**
     * The date and time for when the last change was made to this request. Read-only.
     * @type {Timestamp}
     * @memberof UpdateRequest
     */
    modifiedAt?: Timestamp;
    /**
     * The schedule for which update requests are sent out.
     * @type {Schedule}
     * @memberof UpdateRequest
     */
    schedule?: Schedule;
    /**
     * `User` object containing `name` and `email` of the sender.
     * 
     * @type {MiniUser}
     * @memberof UpdateRequest
     */
    sentBy?: MiniUser;
}

/**
 * Check if a given object implements the UpdateRequest interface.
 */
export function instanceOfUpdateRequest(value: object): value is UpdateRequest {
    return true;
}

export function UpdateRequestFromJSON(json: any): UpdateRequest {
    return UpdateRequestFromJSONTyped(json, false);
}

export function UpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rowIds': json['rowIds'] == null ? undefined : json['rowIds'],
        'columnIds': json['columnIds'] == null ? undefined : json['columnIds'],
        'includeAttachments': json['includeAttachments'] == null ? undefined : json['includeAttachments'],
        'includeDiscussions': json['includeDiscussions'] == null ? undefined : json['includeDiscussions'],
        'layout': json['layout'] == null ? undefined : json['layout'],
        'ccMe': json['ccMe'] == null ? undefined : json['ccMe'],
        'message': json['message'] == null ? undefined : json['message'],
        'sendTo': json['sendTo'] == null ? undefined : ((json['sendTo'] as Array<any>).map(RecipientFromJSON)),
        'subject': json['subject'] == null ? undefined : json['subject'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : TimestampFromJSON(json['createdAt']),
        'modifiedAt': json['modifiedAt'] == null ? undefined : TimestampFromJSON(json['modifiedAt']),
        'schedule': json['schedule'] == null ? undefined : ScheduleFromJSON(json['schedule']),
        'sentBy': json['sentBy'] == null ? undefined : MiniUserFromJSON(json['sentBy']),
    };
}

export function UpdateRequestToJSON(json: any): UpdateRequest {
    return UpdateRequestToJSONTyped(json, false);
}

export function UpdateRequestToJSONTyped(value?: UpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rowIds': value['rowIds'],
        'columnIds': value['columnIds'],
        'includeAttachments': value['includeAttachments'],
        'includeDiscussions': value['includeDiscussions'],
        'layout': value['layout'],
        'ccMe': value['ccMe'],
        'message': value['message'],
        'sendTo': value['sendTo'] == null ? undefined : ((value['sendTo'] as Array<any>).map(RecipientToJSON)),
        'subject': value['subject'],
        'id': value['id'],
        'createdAt': TimestampToJSON(value['createdAt']),
        'modifiedAt': TimestampToJSON(value['modifiedAt']),
        'schedule': ScheduleToJSON(value['schedule']),
        'sentBy': MiniUserToJSON(value['sentBy']),
    };
}

