/* tslint:disable */
/* eslint-disable */
/**
 * Smartsheet OpenAPI Reference
 * Welcome to the OpenAPI reference documentation for the Smartsheet API!  > **IMPORTANT:** > * The Smartsheet API is restricted to users on Business and Enterprise plans > * The <a href=\"https://www.smartsheet.com/legal/developer-program-agreement\" target=\"_blank\" rel=\"noopener noreferrer\">Developer Agreement</a> governs the use of the Smartsheet API and Smartsheet software development kits (SDKs)  **QUICKLINKS**  - **Base URL:**      ```     https://api.smartsheet.com/2.0/     ```  - **Getting started:** <a href=\"https://help.smartsheet.com/articles/2482389-generate-API-key\" target=\"_blank\" rel=\"noopener noreferrer\">Generate an API access token</a> and [make a request](/api/smartsheet/guides/getting-started).  - **Changelog:** See the latest [API updates](/api/smartsheet/changelog).  - **Schemas:** View the [object schemas](/api/smartsheet/openapi/schemas) not explicitly listed in the resource sections.  - **Error codes:** Look up common API [error codes](/api/smartsheet/error-codes).  - **Guides:** Learn various ways of using the API with the help of our [Guides](/api/smartsheet/introduction).  Browse the Smartsheet API operations by resource on the left and start building with the Smartsheet API! 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WebhookAllOfStats
 */
export interface WebhookAllOfStats {
    /**
     * When this webhook last made a callback attempt.
     * @type {Date}
     * @memberof WebhookAllOfStats
     */
    readonly lastCallbackAttempt?: Date;
    /**
     * The number of retries the webhook had performed as of the last callback attempt.
     * @type {number}
     * @memberof WebhookAllOfStats
     */
    readonly lastCallbackAttemptRetryCount?: number;
    /**
     * When this webhook last made a successful callback.
     * @type {Date}
     * @memberof WebhookAllOfStats
     */
    readonly lastSuccessfulCallback?: Date;
}

/**
 * Check if a given object implements the WebhookAllOfStats interface.
 */
export function instanceOfWebhookAllOfStats(value: object): value is WebhookAllOfStats {
    return true;
}

export function WebhookAllOfStatsFromJSON(json: any): WebhookAllOfStats {
    return WebhookAllOfStatsFromJSONTyped(json, false);
}

export function WebhookAllOfStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAllOfStats {
    if (json == null) {
        return json;
    }
    return {
        
        'lastCallbackAttempt': json['lastCallbackAttempt'] == null ? undefined : (new Date(json['lastCallbackAttempt'])),
        'lastCallbackAttemptRetryCount': json['lastCallbackAttemptRetryCount'] == null ? undefined : json['lastCallbackAttemptRetryCount'],
        'lastSuccessfulCallback': json['lastSuccessfulCallback'] == null ? undefined : (new Date(json['lastSuccessfulCallback'])),
    };
}

export function WebhookAllOfStatsToJSON(json: any): WebhookAllOfStats {
    return WebhookAllOfStatsToJSONTyped(json, false);
}

export function WebhookAllOfStatsToJSONTyped(value?: Omit<WebhookAllOfStats, 'lastCallbackAttempt'|'lastCallbackAttemptRetryCount'|'lastSuccessfulCallback'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

