name: Update Coverage Badge

on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-badge:
    name: Update Coverage Badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm run test:coverage
      
      - name: Create badges directory
        run: mkdir -p .github/badges
      
      - name: Generate coverage badge
        run: |
          # Get the coverage percentage from the json-summary report
          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total | .lines.pct')
          ROUNDED_COVERAGE=$(printf "%.0f" $COVERAGE)
          
          # Determine color based on coverage percentage
          if [ $ROUNDED_COVERAGE -lt 50 ]; then
            COLOR="red"
          elif [ $ROUNDED_COVERAGE -lt 70 ]; then
            COLOR="yellow"
          elif [ $ROUNDED_COVERAGE -lt 85 ]; then
            COLOR="green"
          else
            COLOR="brightgreen"
          fi
          
          # Generate badge using shields.io
          curl "https://img.shields.io/badge/coverage-$ROUNDED_COVERAGE%25-$COLOR" > .github/badges/coverage.svg
      
      - name: Commit and push badge
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/badges/coverage.svg'
          message: 'chore: update coverage badge [skip ci]'
          default_author: github_actions